apiVersion: apps/v1
kind: Deployment
metadata: 
  name: simple-node-app-deployment
  namespace: {{.Values.namespace.name}}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector: 
    matchLabels:
      app: simple-node-app
  template:
    metadata:
      labels:
        app: simple-node-app
      
      #checksum/config: {{ include (print $.Chart.Name "/templates/config.yaml") . | sha256sum}}
      #checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum}}
    spec:
      containers:
        - name: simple-node-app
          image: sanjana03/simple-node-app
          ports:
          - containerPort: 80