apiVersion: v1
kind: LimitRange
metadata:
  name: simple-node-app-lr1
spec:
  limits:
  - default:
      cpu: 1
      memory: 512Mi
    defaultRequest:
      cpu: 0.5
      memory: 256Mi
    max:
      cpu: 2
      memory: 4Gi
    min:
      cpu: 200m
      memory: 256Mi
    type: Container
  